version: "3.9"

services:
  wa-gateway:
    build: .
    container_name: wa-gateway
    restart: unless-stopped
    ports:
      - "5001:5001"
    environment:
      - WEBHOOK_URL=https://webhook.wrjunior.my.id
      - JWT_SECRET=CAYfnXKSPlFLGjo8dcsxroUtk5ZcjVpW9sm6f67LcYl2wwFsyKQI5ex4/+/l63Ze
    volumes:
      - ./sessions:/app/sessions # persisten auth
